[workspace]
members = [
    "crates/*"
]
resolver = "2"

[workspace.package]
authors = ["Joshua Radin <jradin16@gmail.com>"]
edition = "2021"
repository = "https://github.com/joshradin/weaver"
license = "MIT OR Apache-2.0"
version = "0.0.0"
readme = "README.md"

