name: build-pipeline
on:
  pull_request:
  push:
    paths:
      - main
jobs:
  verify-integrity:
    name: Verify Integrity
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        run: |
          rustup install stable
      - name: Install dependencies
        run: |
          cargo install cargo-deny
          cargo install cargo-audit
      - run: cargo check --workspace
      - run: cargo deny check
      - run: cargo audit -d /tmp/cargo-audit-repo
  run-unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    needs: [verify-integrity]
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        run: |
          rustup install stable
      - name: Install dependencies
        run: |
          cargo install cargo-nextest
      - run: cargo nextest run --workspace --profile ci-unit -E 'kind(bin) + kind(lib)'
  run-integration-tests:
    name: Run Integration Tests
    runs-on: ubuntu-latest
    needs: [ run-unit-tests ]
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        run: |
          rustup install stable
      - name: Install dependencies
        run: |
          cargo install cargo-nextest
      - run: cargo nextest run --workspace --profile ci-int -E 'kind(test)'