name: build-pipeline
on:
  pull_request:
  push:
    paths:
      - main
jobs:
  prepare:
    name: Initialize workspace
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        run: rustup toolchain install stable --profile minimal
      - uses: Swatinem/rust-cache@v2
      - name: Install binary dependencies
        run: |
          cargo install cargo-deny
          cargo install cargo-audit
          cargo install cargo-nextest
      - name: Build project
        run: cargo build
  integrity:
    name: Verify Integrity
    runs-on: ubuntu-latest
    needs: [ prepare ]
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        run: rustup toolchain install stable --profile minimal
      - uses: Swatinem/rust-cache@v2
      - name: Install binary dependencies
        run: |
          cargo install cargo-deny
          cargo install cargo-audit
      - run: cargo check --workspace
      - run: cargo deny check
      - run: cargo audit -d /tmp/cargo-audit-repo
  unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    needs: [integrity]
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        run: rustup toolchain install stable --profile minimal
      - uses: Swatinem/rust-cache@v2
      - name: Install binary dependencies
        run: |
          cargo install cargo-nextest
      - run: cargo nextest run --workspace --profile ci-unit -E 'kind(bin) + kind(lib)'
  integration-tests:
    name: Run Integration Tests
    runs-on: ubuntu-latest
    needs: [ integrity ]
    steps:
      - uses: actions/checkout@v4
      - name: Install binary dependencies
        run: |
          cargo install cargo-nextest
      - run: cargo nextest run --workspace --profile ci-int -E 'kind(test)'